resolver: nightly-2017-02-03

packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process-client-server.git
    commit: 0cefe5eb5eda5b3c5c9f61517462172e2f9e086a
  extra-dep: true

extra-deps:
- distributed-process-0.6.6         # missing snapshot
- distributed-process-extras-0.3.1  # missing snapshot
- distributed-process-async-0.2.4   # missing snapshot
- distributed-process-systest-0.1.1 # missing prior to Jan-2017
- rematch-0.2.0.0
