resolver: lts-11.9

packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process-client-server.git
    commit: c2bd4133fed16cfeeed09f8351e5cabd60ab64db
  extra-dep: true

extra-deps:
- distributed-process-0.7.3
- distributed-process-extras-0.3.4  # missing snapshot
- distributed-process-async-0.2.5   # missing snapshot
- rematch-0.2.0.0

